"""Agrega email, is_admin, activo y permisos por modulo a usuarios

Revision ID: 42ab85879954
Revises: 96097690dc69
Create Date: 2026-08-31 18:45:30.448603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ab85879954'
down_revision = '96097690dc69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('puede_clientes', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('puede_lotes', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('puede_productos', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('puede_recetas', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.create_unique_constraint('uq_usuarios_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('uq_usuarios_email', type_='unique')
        batch_op.drop_column('puede_recetas')
        batch_op.drop_column('puede_productos')
        batch_op.drop_column('puede_lotes')
        batch_op.drop_column('puede_clientes')
        batch_op.drop_column('activo')
        batch_op.drop_column('is_admin')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
