"""Agrega poligono y agromonitoring_id a lotes

Revision ID: 47561bb6e179
Revises: bb9750930681
Create Date: 2026-09-05 19:05:05.453787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47561bb6e179'
down_revision = 'bb9750930681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poligono', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('agromonitoring_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lotes', schema=None) as batch_op:
        batch_op.drop_column('agromonitoring_id')
        batch_op.drop_column('poligono')

    # ### end Alembic commands ###
