"""Agrega precio a productos y precio_unitario/importe_total a recetas_detalle

Revision ID: 543bde80aed9
Revises: 42ab85879954
Create Date: 2026-08-31 19:41:50.332224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543bde80aed9'
down_revision = '42ab85879954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', sa.Float(), nullable=False, server_default=sa.text('0')))

    with op.batch_alter_table('recetas_detalle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_unitario', sa.Float(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('importe_total', sa.Float(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recetas_detalle', schema=None) as batch_op:
        batch_op.drop_column('importe_total')
        batch_op.drop_column('precio_unitario')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('precio')

    # ### end Alembic commands ###
