"""Esquema inicial: usuarios, clientes, productos, lotes, recetas

Revision ID: 96097690dc69
Revises: 
Create Date: 2026-08-28 14:11:54.915197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96097690dc69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuit', sa.String(length=20), nullable=True),
    sa.Column('razon_social', sa.String(length=150), nullable=False),
    sa.Column('domicilio', sa.String(length=150), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('codigo_postal', sa.String(length=20), nullable=True),
    sa.Column('localidad', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('id_coniva', sa.String(length=100), nullable=True),
    sa.Column('latitud', sa.String(length=50), nullable=True),
    sa.Column('longitud', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denominacion_comercial', sa.String(length=150), nullable=False),
    sa.Column('principio_activo', sa.String(length=150), nullable=False),
    sa.Column('concentracion', sa.Float(), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('cultivo', sa.String(length=100), nullable=True),
    sa.Column('superficie_ha', sa.Float(), nullable=False),
    sa.Column('latitud', sa.String(length=50), nullable=True),
    sa.Column('longitud', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_alta', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_receta', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('hectareas', sa.Float(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_receta')
    )
    op.create_table('recetas_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('dosis', sa.Float(), nullable=False),
    sa.Column('cantidad_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recetas_detalle')
    op.drop_table('recetas')
    op.drop_table('lotes')
    op.drop_table('usuarios')
    op.drop_table('productos')
    op.drop_table('clientes')
    # ### end Alembic commands ###
