"""Agrega tabla parametros para combos configurables

Revision ID: a77510f8f658
Revises: 543bde80aed9
Create Date: 2026-09-02 18:32:16.001753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a77510f8f658'
down_revision = '543bde80aed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parametros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.String(length=150), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoria', 'valor', name='uq_parametro_categoria_valor')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parametros')
    # ### end Alembic commands ###
